version: '3'
services:
  go-api:
    build:
      context: ./api_go
      dockerfile: Dockerfile
    ports:
      - '4200:8080'
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
