name: Run tests for Web Portal

on:
    push:
    pull_request:
        branches:
        - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Check test status and prevent PR merge on failure
        run: |
          if [ ${{ job.status }} == 'failure' ]; then
            echo "Tests failed. This pull request cannot be merged."
            exit 1
          fi
